config/routes.rb
BigDataRailsServer::Application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :cities

  get 'twitter/all_city_search'      => 'twitter#all_city_search'
  get 'twitter/lat_lon_sample'       => 'twitter#lat_lon_sample'
  get 'twitter/query'                => 'twitter#query'
  get 'twitter/elasticsearch_sample' => 'twitter#elasticsearch_sample'
  get 'twitter/elasticsearch_query'  => 'twitter#elasticsearch_query'

  root 'twitter#index'

end

app/models/city.rb
require 'csv'

class City < ActiveRecord::Base

  #attr_accessible :name, :latitude, :longitude

  def self.import(tsv_path)
    raise "Not a valid TSV file" unless File.basename(tsv_path).match(/\.tsv$/)
    parsed_file = CSV.read(tsv_path, { :col_sep => "\t" })
    lat_col = parsed_file[0].each_with_index.detect{ |value, index| value.match /^lat/i }[-1]
    long_col = parsed_file[0].each_with_index.detect{ |value, index| value.match /^long/i }[-1]
    name_col = parsed_file[0].each_with_index.detect{ |value, index| value.match /^(cit|name)/i }[-1]

    parsed_file[1..-1].each do |city_arr|
      city = self.new name: city_arr[name_col], longitude: city_arr[long_col], latitude: city_arr[lat_col]
      city.save!
    end
  end

end

app/models/tweet.rb
class Tweet
  extend SimpleElasticSearch

  ELASTIC_SEARCH_TWEET_TYPE = 'tweet'
  @@_es_client = Elasticsearch::Client.new

  def self.all
    results = self.all_docs_in_index $elasticsearch_config[:host], $elasticsearch_config[:port], $elasticsearch_index
    results.hits.hits
  end

  def self.query(query)
    result = elasicsearch_client.search(
      index: $elasticsearch_index,
      body: query
    )
    hits = get_hits result
    ret = hits.collect do |r|
      begin
        [r['_source']['lat'], r['_source']['lon']]
      rescue
        nil
      end
    end

    ret.delete nil
    ret
  end

  def self.search_str(str)
    query = {
        query:{
            query_string:{
                query: (str)
            }
        }
    }
    result = self.search $elasticsearch_config[:host], $elasticsearch_config[:port], $elasticsearch_index, query, ELASTIC_SEARCH_TWEET_TYPE
    result.hits.hits
  end

  def self.elasicsearch_client
    @@_es_client
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #http_basic_authenticate_with name: "big-data", password: "big-things"
  skip_before_filter :verify_authenticity_token, :if => Proc.new { |c| c.request.format == 'application/json' }
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render action: 'show', status: :created, location: @city }
      else
        format.html { render action: 'new' }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name, :latitude, :longitude)
    end
end

app/controllers/twitter_controller.rb
class TwitterController < ApplicationController

  RADIUS = '10mi'

  def index; end

  def all_city_search
    city_geos = City.all.collect{ |city| [city.latitude, city.longitude] }
    radius = params[:radius] || RADIUS

    all_tweets=[]
    search_threads=[]
    city_geos[0..4].each do |city_geo|
      search_threads << Thread.new do
        geo_str = "#{city_geo[0]}, #{city_geo[-1]}, #{radius}"
        Rails.logger.debug "All city query: #{params[:query_str]} #{geo_str}"

        begin
          result = client.search( params[:query_str], {geocode: geo_str, count: 5} ).collect(&:text)
          Rails.logger.debug result
          all_tweets.merge result
        rescue => e
          puts e.message
          sleep 10
          retry
        end
      end
    end
    search_threads.each(&:join)

    respond_to do |format|
      format.json { render json: all_tweets.to_json }
      format.text { render text: all_tweets.inspect }
    end
  end

  def query
    result = Twitter.search_str( query )
    respond_to do |format|
      format.json{ render text: result.inject(""){ |acc, tweet| "#{acc} #{tweet.text}\n\n" } and return }
    end
  end

  #GET /twitter/elasticsearch_query?query='{
  #   "query":{
  #     "stuff":{}
  #   }
  # }'

  def elasticsearch_query
    query_obj = params[:query].to_hash
    Rails.logger.debug "Query object: #{query_obj}"
    result = Tweet.query query_obj

    respond_to do |format|
      format.json{ render json: result }
    end
  end

  # Sample of all tweets in elasticsearch
  def elasticsearch_sample
    results = Tweet.all
    if params[:geo]
      results = results.collect do |redis_arr|
        tweet = JSON.parse redis_arr[-1]
        [tweet['lat'].to_f, tweet['lon'].to_f]
      end
      results.delete []
    end

    respond_to do |format|
      format.json{ render json: results.to_json }
    end
  end

  # lat lon sample from all tweets in redis
  def lat_lon_sample
    results = $redis.hgetall $redis_keys[:enhanced_tweets]
    results = results.collect do |redis_arr|
      tweet = JSON.parse redis_arr[-1]
      [tweet['lat'].to_f, tweet['lon'].to_f]
    end
    results.delete []

    respond_to do |format|
      format.json{ render json: results.to_json }
    end
  end

  private

  def client
    @@client ||= init_client
  end

  def init_client
    tw_config = YAML.load_file( File.join(Rails.root, 'config','twitter.yml' ) )[Rails.env]

    Rails.logger.debug tw_config
    Twitter::REST::Client.new do |config|
      config.consumer_key        = tw_config["api_key"]
      config.consumer_secret     = tw_config["api_secret"]
      config.access_token        = tw_config["access_token"]
      config.access_token_secret = tw_config["access_token_secret"]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/twitter_helper.rb
module TwitterHelper
end

app/views/cities/_form.html.erb
<%= form_for(@city) do |f| %>
  <% if @city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% @city.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing city</h1>

<%= render 'form' %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<h1>Listing cities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.name %></td>
        <td><%= city.latitude %></td>
        <td><%= city.longitude %></td>
        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>

app/views/cities/new.html.erb
<h1>New city</h1>

<%= render 'form' %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @city.name %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @city.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @city.longitude %>
</p>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>We Do Big Data</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyC6t1AVEXxLUq4OvaIpclcYgD6R-NRilt4&sensor=true&libraries=visualization"></script>
	<%= requirejs_include_tag "application" %> 
	<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/twitter/index.html.erb
<div style="margin-top: 50px; width: 100%; height: 100%;">
	<div data-ng-view></div>
</div>